import React, { useState, useEffect } from 'react';
import { getReports } from '../../services/api';
import { FaDownload, FaFileAlt, FaPoll, FaClock, FaFilter, FaFileCsv } from 'react-icons/fa';
import EngagementChart from './components/EngagementChart';
import PollAnalyticsChart from './components/PollAnalyticsChart';
import './Reports.css';

const OfficialReports = () => {
  const [reportData, setReportData] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);
  const [filters, setFilters] = useState({
    startDate: '',
    endDate: '',
    category: 'All Categories',
    location: 'All Locations',
  });
  const [showFilters, setShowFilters] = useState(false);
// eslint-disable-next-line react-hooks/exhaustive-deps
  useEffect(() => {
    fetchReport();
  }, []);

  const fetchReport = async () => {
    try {
      setLoading(true);
      const filterParams = {};
      if (filters.startDate) filterParams.startDate = filters.startDate;
      if (filters.endDate) filterParams.endDate = filters.endDate;
      if (filters.category !== 'All Categories') filterParams.category = filters.category;
      if (filters.location !== 'All Locations') filterParams.location = filters.location;

      const { data } = await getReports(filterParams);
      setReportData(data);
    } catch (err) {
      console.error('Failed to generate report:', err);
      setError('Failed to load report data');
    } finally {
      setLoading(false);
    }
  };

  const handleFilterChange = (key, value) => {
    setFilters(prev => ({ ...prev, [key]: value }));
  };

  const applyFilters = () => {
    fetchReport();
    setShowFilters(false);
  };

  const resetFilters = () => {
    setFilters({
      startDate: '',
      endDate: '',
      category: 'All Categories',
      location: 'All Locations',
    });
  };

  const handleExportPDF = () => {
    window.print();
  };

  const handleExportCSV = () => {
    if (!reportData) return;
    
    // Create CSV content
    let csv = 'Civix Report\n\n';
    csv += `Generated: ${new Date().toLocaleString()}\n`;
    csv += `Generated By: ${reportData.exportMetadata?.generatedBy || 'Unknown'}\n\n`;
    
    csv += 'Metrics\n';
    csv += `Total Signatures,${reportData.metrics.totalSignatures}\n`;
    csv += `Total Votes,${reportData.metrics.totalVotes}\n`;
    csv += `Resolved Issues,${reportData.metrics.resolvedIssues}\n`;
    csv += `Unresolved Issues,${reportData.metrics.unresolvedIssues}\n`;
    csv += `Active Polls,${reportData.metrics.activePolls}\n\n`;
    
    csv += 'Top Categories\n';
    reportData.petitionAnalytics.topCategories.forEach(cat => {
      csv += `${cat.name},${cat.count}\n`;
    });
    
    // Download CSV
    const blob = new Blob([csv], { type: 'text/csv' });
    const url = window.URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `civix-report-${new Date().toISOString().split('T')[0]}.csv`;
    a.click();
    window.URL.revokeObjectURL(url);
  };

  const formatNumber = (num) => {
    if (num === undefined || num === null) return '0';
    return num.toLocaleString();
  };

  const formatDate = (dateString) => {
    if (!dateString) return 'N/A';
    return new Date(dateString).toLocaleDateString();
  };

  if (loading) {
    return (
      <div className="reports-container">
        <div className="reports-loading">
          <p>Generating report...</p>
        </div>
      </div>
    );
  }

  if (error || !reportData) {
    return (
      <div className="reports-container">
        <div className="reports-error">
          <p>{error || 'No data available'}</p>
          <button onClick={fetchReport}>Retry</button>
        </div>
      </div>
    );
  }

  const {
    metrics = {},
    engagementGrowth = [],
    pollVotesTrend = [],
    signaturesTrend = [],
    petitionAnalytics = {},
    pollAnalytics = {},
    adminLogs = [],
    filters: filterOptions,
    exportMetadata,
  } = reportData;

  const topCategories = petitionAnalytics.topCategories || [];
  const statusDistribution = petitionAnalytics.statusDistribution || [];
  const mostActivePolls = pollAnalytics.mostActivePolls || [];
  const mostDiscussed = pollAnalytics.mostDiscussed || [];
  const engagementBreakdown = pollAnalytics.engagementBreakdown || [];

  return (
    <div className="reports-container">
      <div className="reports-header">
        <div>
          <h1>Analytics Dashboard</h1>
          <p>Comprehensive insights and administrative logs for District 1</p>
        </div>
        <div className="header-actions">
          <button 
            className="filter-btn" 
            onClick={() => setShowFilters(!showFilters)}
          >
            <FaFilter /> Filters
          </button>
          <button className="export-pdf-btn" onClick={handleExportPDF}>
            <FaDownload /> Export PDF
          </button>
          <button className="export-csv-btn" onClick={handleExportCSV}>
            <FaFileCsv /> Export CSV
          </button>
        </div>
      </div>

      {/* Filter Panel */}
      {showFilters && (
        <div className="filter-panel">
          <div className="filter-row">
            <div className="filter-group">
              <label>Start Date</label>
              <input
                type="date"
                value={filters.startDate}
                onChange={(e) => handleFilterChange('startDate', e.target.value)}
              />
            </div>
            <div className="filter-group">
              <label>End Date</label>
              <input
                type="date"
                value={filters.endDate}
                onChange={(e) => handleFilterChange('endDate', e.target.value)}
              />
            </div>
            <div className="filter-group">
              <label>Category</label>
              <select
                value={filters.category}
                onChange={(e) => handleFilterChange('category', e.target.value)}
              >
                {filterOptions?.availableCategories?.map((cat) => (
                  <option key={cat} value={cat}>{cat}</option>
                ))}
              </select>
            </div>
            <div className="filter-group">
              <label>Location</label>
              <select
                value={filters.location}
                onChange={(e) => handleFilterChange('location', e.target.value)}
              >
                {filterOptions?.availableLocations?.map((loc) => (
                  <option key={loc} value={loc}>{loc}</option>
                ))}
              </select>
            </div>
          </div>
          <div className="filter-actions">
            <button className="apply-btn" onClick={applyFilters}>Apply Filters</button>
            <button className="reset-btn" onClick={resetFilters}>Reset</button>
          </div>
        </div>
      )}

      {/* Metrics Cards */}
      <div className="metrics-grid">
        <div className="metric-card">
          <div className="metric-icon blue">
            <FaFileAlt />
          </div>
          <div className="metric-content">
            <div className="metric-label">Total Signatures</div>
            <div className="metric-value">{formatNumber(metrics.totalSignatures)}</div>
            <div className="metric-growth positive">+{metrics.signaturesGrowth}%</div>
          </div>
        </div>

        <div className="metric-card">
          <div className="metric-icon purple">
            <FaPoll />
          </div>
          <div className="metric-content">
            <div className="metric-label">Total Votes</div>
            <div className="metric-value">{formatNumber(metrics.totalVotes)}</div>
            <div className="metric-growth positive">+{metrics.votesGrowth}%</div>
          </div>
        </div>

        <div className="metric-card">
          <div className="metric-icon green">
            <svg viewBox="0 0 24 24" fill="currentColor" width="48" height="48">
              <path d="M9 16.17L4.83 12l-1.42 1.41L9 19 21 7l-1.41-1.41L9 16.17z"/>
            </svg>
          </div>
          <div className="metric-content">
            <div className="metric-label">Resolved Issues</div>
            <div className="metric-value">{formatNumber(metrics.resolvedIssues)}</div>
          </div>
        </div>

        <div className="metric-card">
          <div className="metric-icon red">
            <svg viewBox="0 0 24 24" fill="currentColor" width="48" height="48">
              <path d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm1 15h-2v-2h2v2zm0-4h-2V7h2v6z"/>
            </svg>
          </div>
          <div className="metric-content">
            <div className="metric-label">Unresolved Issues</div>
            <div className="metric-value">{formatNumber(metrics.unresolvedIssues)}</div>
          </div>
        </div>

        <div className="metric-card">
          <div className="metric-icon orange">
            <svg viewBox="0 0 24 24" fill="currentColor" width="48" height="48">
              <path d="M4 4h16v16H4V4zm2 2v12h12V6H6zm2 2h8v2H8V8zm0 4h8v2H8v-2zm0 4h5v2H8v-2z"/>
            </svg>
          </div>
          <div className="metric-content">
            <div className="metric-label">Active Polls</div>
            <div className="metric-value">{formatNumber(metrics.activePolls)}</div>
          </div>
        </div>
      </div>

      <EngagementChart
        data={engagementGrowth}
        pollTrend={pollVotesTrend}
        signatureTrend={signaturesTrend}
      />

      {/* Analytics Sections */}
      <div className="analytics-grid">
        {/* Petition Analytics */}
        <div className="analytics-section">
          <div className="analytics-header">
            <FaFileAlt className="analytics-icon" />
            <h3>Petition Analytics</h3>
          </div>

          <div className="analytics-subsection">
            <h4>TOP CATEGORIES</h4>
            <div className="bar-chart-horizontal">
              {topCategories.map((cat, i) => {
                const maxCount = topCategories.length ? Math.max(...topCategories.map(c => c.count)) : 0;
                const width = maxCount > 0 ? (cat.count / maxCount) * 100 : 0;
                const colors = ['#3b82f6', '#10b981', '#f59e0b', '#ef4444', '#8b5cf6'];
                return (
                  <div key={i} className="bar-item">
                    <div className="bar-label">{cat.name}</div>
                    <div className="bar-container">
                      <div
                        className="bar-fill"
                        style={{ width: `${width}%`, backgroundColor: colors[i] || '#3b82f6' }}
                      />
                    </div>
                    <div className="bar-value">{cat.count}</div>
                  </div>
                );
              })}
            </div>
          </div>

          <div className="analytics-subsection">
            <h4>STATUS DISTRIBUTION</h4>
            <div className="donut-chart-container">
              <svg width="200" height="200" className="donut-chart">
                <circle
                  cx="100"
                  cy="100"
                  r="80"
                  fill="none"
                  stroke="#e5e7eb"
                  strokeWidth="40"
                />
                {(() => {
                  const total = statusDistribution.reduce((sum, s) => sum + s.count, 0);
                  let currentOffset = 0;
                  const colors = { 'Active': '#3b82f6', 'Under Review': '#10b981', 'Closed': '#6b7280' };
                  return statusDistribution.map((status, i) => {
                    const percentage = total > 0 ? (status.count / total) * 100 : 0;
                    const strokeDasharray = `${(percentage / 100) * 502.65} 502.65`;
                    const offset = currentOffset;
                    currentOffset -= (percentage / 100) * 502.65;
                    return (
                      <circle
                        key={i}
                        cx="100"
                        cy="100"
                        r="80"
                        fill="none"
                        stroke={colors[status.status] || '#3b82f6'}
                        strokeWidth="40"
                        strokeDasharray={strokeDasharray}
                        strokeDashoffset={offset}
                        transform="rotate(-90 100 100)"
                      />
                    );
                  });
                })()}
              </svg>
              <div className="donut-legend">
                {statusDistribution.map((status, i) => {
                  const colors = { 'Active': '#3b82f6', 'Under Review': '#10b981', 'Closed': '#6b7280' };
                  return (
                    <div key={i} className="donut-legend-item">
                      <div className="donut-legend-color" style={{ backgroundColor: colors[status.status] || '#3b82f6' }}></div>
                      <span>{status.status}: {status.count}</span>
                    </div>
                  );
                })}
              </div>
            </div>
          </div>
        </div>

        {/* Poll Analytics */}
        <div className="analytics-section">
          <div className="analytics-header">
            <FaClock className="analytics-icon" />
            <h3 className="poll-analytics-title">Poll Analytics</h3>
          </div>

          <div className="analytics-subsection">
            <h4>MOST ACTIVE POLLS (VOTES)</h4>
            <PollAnalyticsChart polls={mostActivePolls} />
          </div>

          <div className="analytics-subsection">
            <h4>MOST DISCUSSED (COMMENTS)</h4>
            <div className="bar-chart-horizontal">
              {mostDiscussed.map((poll, i) => {
                const maxComments = mostDiscussed.length ? Math.max(...mostDiscussed.map(p => p.comments)) : 0;
                const width = maxComments > 0 ? (poll.comments / maxComments) * 100 : 0;
                return (
                  <div key={i} className="bar-item">
                    <div className="bar-label">{poll.question.length > 30 ? poll.question.substring(0, 30) + '...' : poll.question}</div>
                    <div className="bar-container">
                      <div
                        className="bar-fill"
                        style={{ width: `${width}%`, backgroundColor: '#ec4899' }}
                      />
                    </div>
                    <div className="bar-value">{poll.comments}</div>
                  </div>
                );
              })}
            </div>
          </div>

          {/* Poll Engagement Breakdown */}
          {engagementBreakdown && engagementBreakdown.length > 0 && (
            <div className="analytics-subsection">
              <h4>POLL ENGAGEMENT BREAKDOWN</h4>
              <div className="engagement-breakdown">
                {engagementBreakdown.map((poll, i) => (
                  <div key={i} className="breakdown-item">
                    <div className="breakdown-question">{poll.question}</div>
                    <div className="breakdown-stats">
                      <span>Total Votes: {poll.totalVotes}</span>
                      <span>Options: {poll.options?.length || 0}</span>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          )}
        </div>
      </div>

      {/* Admin Logs Section */}
      {adminLogs && adminLogs.length > 0 && (
        <div className="admin-logs-section">
          <div className="analytics-header">
            <FaClock className="analytics-icon" />
            <h3>Admin Activity Logs</h3>
          </div>
          <div className="admin-logs-table">
            <div className="admin-logs-header">
              <div>Type</div>
              <div>Action</div>
              <div>Target</div>
              <div>Officer</div>
              <div>Timestamp</div>
            </div>
            {adminLogs.map((log, i) => (
              <div key={i} className="admin-logs-row">
                <div>{log.type}</div>
                <div>{log.action}</div>
                <div className="log-target">
                  {(log.target || 'N/A').length > 40
                    ? `${(log.target || 'N/A').substring(0, 40)}...`
                    : log.target || 'N/A'}
                </div>
                <div>{log.officer}</div>
                <div>{formatDate(log.timestamp)}</div>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Export Metadata */}
      {exportMetadata && (
        <div className="export-metadata">
          <p><strong>Report Generated:</strong> {formatDate(exportMetadata.generatedAt)}</p>
          <p><strong>Generated By:</strong> {exportMetadata.generatedBy}</p>
          <p><strong>Available Formats:</strong> {exportMetadata.formats?.join(', ')}</p>
        </div>
      )}
    </div>
  );
};

export default OfficialReports;

